config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "minutes#index"
  resources :minutes do
    resources :comments, only: [:new, :create, :edit, :update, :destroy]
    resources :to_do_lists, only: [:new, :create, :edit, :update]
    collection do
      get 'search'
    end
    collection do
      get 'search_me'
    end
    collection do
      get 'search_not_close'
    end
    resources :pins, only: [:create, :destroy]
    resources :closes, only: [:create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/close.rb
class Close < ApplicationRecord
  belongs_to :minute

  validates :minute_id, uniqueness: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :minute
  # has_many_attached :images

  validates :title, presence: true
end

app/models/minute.rb
class Minute < ApplicationRecord
  belongs_to :user
  has_many_attached :images
  has_many :comments, dependent: :destroy
  has_one :to_do_list, dependent: :destroy
  has_many :pins, dependent: :destroy
  has_many :closes, dependent: :destroy

  with_options presence: true do
    validates :title
    validates :project_name
    validates :participate_member
    validates :meeting_date, format: { with: %r{\A[0-9]{4}/[0-9]{1,2}/[0-9]{1,2}\z} }
    validates :all_complete_date, format: { with: %r{\A[0-9]{4}/[0-9]{1,2}/[0-9]{1,2}\z} }
    validates :content
  end

  def self.search(search)
    if search != ''
      Minute.where('title LIKE(?)', "%#{search}%")
            .or(Minute.where('project_name LIKE(?)', "%#{search}%"))
            .or(Minute.where('participate_member LIKE(?)', "%#{search}%"))
            .or(Minute.where('meeting_date LIKE(?)', "%#{search}%"))
            .or(Minute.where('all_complete_date LIKE(?)', "%#{search}%"))
            .or(Minute.where('content LIKE(?)', "%#{search}%"))
    else
      Minute.all.order(id: 'DESC')
    end
  end
end

app/models/pin.rb
class Pin < ApplicationRecord
  belongs_to :user
  belongs_to :minute

  validates :user_id, uniqueness: { scope: :minute_id }
end

app/models/to_do_list.rb
class ToDoList < ApplicationRecord
  belongs_to :user
  belongs_to :minute

  validates :list1, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  with_options presence: true do
    validates :last_name
    validates :first_name
    validates :employee_number, format: { with: /\A[0-9]{5}\z/ }
  end

  has_many :minutes
  has_many :comments
  has_many :to_do_lists
  has_many :pins
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def basic_auth
    authenticate_or_request_with_http_basic do |_username, _password|
      username = ENV['BASIC_AUTH_USER'] && password = ENV['BASIC_AUTH_PASSWORD']
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :employee_number])
  end
end

app/controllers/closes_controller.rb
class ClosesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_close
  before_action :not_user_permitted

  def create
    @close = Close.create(minute_id: @minute.id)
  end

  def destroy
    @close = Close.find_by(minute_id: @minute.id)
    @close.destroy
  end

  private

  def set_close
    @minute = Minute.find(params[:minute_id])
  end

  def not_user_permitted
    redirect_to minute_path(@minute.id) unless current_user.id == @minute.user_id
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_comment, only: [:edit, :update, :destroy]
  before_action :not_user_permitted, only: [:edit, :destroy]

  def new
    @comment = Comment.new
  end

  def create
    @comment = Comment.new(comment_params)
    if @comment.save
      redirect_to minute_path(params[:minute_id])
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @comment.update(comment_params)
      redirect_to minute_path(params[:minute_id])
    else
      render :edit
    end
  end

  def destroy
    @comment.destroy
    redirect_to minute_path(params[:minute_id])
  end

  private

  def comment_params
    params.require(:comment).permit(:title).merge(user_id: current_user.id, minute_id: params[:minute_id])
  end

  def set_comment
    @comment = Comment.find_by(id: params[:id], minute_id: params[:minute_id])
  end

  def not_user_permitted
    redirect_to root_path unless @comment.user_id == current_user.id
  end
end

app/controllers/minutes_controller.rb
class MinutesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_minute, only: [:show, :edit, :update, :destroy]
  before_action :not_user_permitted, only: [:edit, :destroy]
  before_action :minute_pin, only: [:index, :show, :search, :search_me, :search_not_close]

  def index
    @minutes = Minute.all.order(id: 'DESC')
    pin = Pin.where(user_id: current_user.id).pluck(:minute_id)
    @minute_pin = Minute.find(pin)
  end

  def new
    @minute = Minute.new
  end

  def create
    @minute = Minute.new(minute_params)
    if @minute.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @comments = @minute.comments
    @to_do_list = @minute.to_do_list
  end

  def edit
  end

  def update
    if @minute.update(minute_params)
      redirect_to minute_path(@minute.id)
    else
      render :edit
    end
  end

  def destroy
    @minute.destroy
    redirect_to root_path
  end

  def search
    @minutes = Minute.search(params[:keyword])
  end

  def search_me
    @minutes = Minute.where(user_id: current_user.id).order(id: 'DESC')
  end

  def search_not_close
    @minutes = Minute.left_joins(:closes).where(closes: { minute_id: nil }).order(id: 'DESC')
  end

  private

  def minute_params
    params.require(:minute).permit(:title, :project_name, :participate_member, :meeting_date, :all_complete_date, :content,
                                   images: []).merge(user_id: current_user.id)
  end

  def set_minute
    @minute = Minute.find(params[:id])
  end

  def not_user_permitted
    redirect_to root_path unless @minute.user_id == current_user.id
  end

  def minute_pin
    pin = Pin.where(user_id: current_user.id).pluck(:minute_id)
    @minute_pin = Minute.find(pin)
  end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_minute

  def create
    @pin = Pin.create(user_id: current_user.id, minute_id: @minute.id)
  end

  def destroy
    @pin = Pin.find_by(user_id: current_user.id, minute_id: @minute.id)
    @pin.destroy
  end

  private

  def set_minute
    @minute = Minute.find(params[:minute_id])
  end
end

app/controllers/to_do_lists_controller.rb
class ToDoListsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_to_do_list, only: [:edit, :update]

  def new
    @to_do_list = ToDoList.new
  end

  def create
    @to_do_list = ToDoList.new(to_do_list_params)
    if @to_do_list.save
      redirect_to minute_path(params[:minute_id])
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @to_do_list.update(to_do_list_params)
      redirect_to minute_path(params[:minute_id])
    else
      render :edit
    end
  end

  private

  def to_do_list_params
    params.require(:to_do_list)
          .permit(:list1, :list2, :list3, :list4, :list5, :list6, :list7, :list8, :list9, :list10,
                  :checked_list1, :checked_list2, :checked_list3, :checked_list4, :checked_list5,
                  :checked_list6, :checked_list7, :checked_list8, :checked_list9, :checked_list10)
          .merge(user_id: current_user.id, minute_id: params[:minute_id])
  end

  def set_to_do_list
    @to_do_list = ToDoList.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/closes_helper.rb
module ClosesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/minutes_helper.rb
module MinutesHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/helpers/to_do_lists_helper.rb
module ToDoListsHelper
end

app/views/comments/edit.html.erb
<div class="main-contents">
  <h2>コメント編集ページ</h2>
    <%= form_with(model:@comment, url:minute_comment_path, class:"form", local: true) do |f| %>
      <%= render "shared/error_messages", locals:{model: @comment}, model: f.object %>

      <div class="title-form">
        <div class="form-title">
        コメントを入力してください
        </div>
        <%= f.text_area :title, class:"comment-form" %>
      </div>

      <div class="submit-form">
        <%= f.submit "登録する", class:"submit-btn" %>
      </div>

    <% end %>

    <%= link_to "トップページに戻る", root_path, class:"back-top-page"%>
</div>

app/views/comments/new.html.erb
<div class="main-contents">
  <h2>コメント投稿ページ</h2>
    <%= form_with(model:@comment, url:minute_comments_path, class:"form", local: true) do |f| %>
      <%= render "shared/error_messages", locals:{model: @comment}, model: f.object %>

      <div class="title-form">
        <div class="form-title">
        コメントを入力してください
        </div>
        <%= f.text_area :title, class:"comment-form" %>
      </div>

      <div class="submit-form">
        <%= f.submit "登録する", class:"submit-btn" %>
      </div>

    <% end %>

    <%= link_to "トップページに戻る", root_path, class:"back-top-page"%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Minutes-App-33991</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/3.18.1/build/cssreset/cssreset-min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/minutes/_minute.html.erb
<div class="minute">
  
  <%= link_to minute_path(minute.id) do%>
    <%# close済みの議事録は各カードにclose済を表示する %>
    <div class="close-status">
      <% if minute.closes.present? %>
        <div class="closed">
          <span>close済</span>
        </div>
      <% else %>
        <div class="open">
        </div>
      <% end %>
    </div>

    <%# 議事録各カード一覧表示 %>
    <div class="minute-content">
      <div class="minute.title">
        会議題目：<%= minute.title %>
      </div>
      <div class="minute-meeting_date">
        会議開催日：<%= minute.meeting_date %>
      </div>
      <div class="minute-project_name">
        プロジェクト名：<%= minute.project_name %>
      </div>
      <div class="minute-participate_member">
        参加メンバー：<%= minute.participate_member %>
      </div>
      <div class="minute-post_user_name">
        登録者：<%= minute.user.last_name+minute.user.first_name %>
      </div>
    </div>
    
  <% end %>
</div>

app/views/minutes/_short_minute.html.erb
<div class="minute">
  <%= link_to minute_path(minute.id) do%>
        <div class="close-status">
      <% if minute.closes.present? %>
        <div class="closed">
          <span>close済</span>
        </div>
      <% end %>
    </div>
          <div class="minute.title">
            会議題目：<%= minute.title %>
          </div>
          <div class="minute-meeting_date">
            会議開催日：<%= minute.meeting_date %>
          </div>
          <div class="minute-project_name">
            プロジェクト名：<%= minute.project_name %>
          </div>
          <div class="minute-post_user_name">
            登録者：<%= minute.user.last_name+minute.user.first_name %>
          </div>
  <% end %>
</div>

app/views/minutes/edit.html.erb
<div class="main-contents">
    <h2>■議事録 編集ページ</h2>

    <%= form_with(model:@minute, url:minute_path, class:"form", local: true) do |f| %>
    <%= render "shared/error_messages", locals:{model: @minute}, model: f.object %>

    <div class="title-form">
      <div class="form-title">
        会議名
        <br><span class="indispensable">（必須）</span>
      </div>
      <%= f.text_field :title, class:"minutes-form", placeholder:"例)Aプロジェクト キックオフ会議"%>
    </div>

    <div class="project_name-form">
      <div class="form-title">
        プロジェクト名
        <br><span class="indispensable">（必須）</span>
      </div>
      <%= f.text_field :project_name, class:"minutes-form", placeholder:"例)Aプロジェクト"%>
    </div>

    <div class="participate_member-form">
      <div class="form-title">
        会議参加者
        <br><span class="indispensable">（必須）</span>
      </div>
      <%= f.text_area :participate_member, class:"minutes-form-area", placeholder:"例)X社X部 鈴木様, C課 田中さん"%>
    </div>

    <div class="meeting_date-form">
      <div class="form-title">
        会議開催日
        <br><span class="indispensable">（必須, ※ 西暦4桁/月/日 で登録してください)</span>
      </div>
      <%= f.text_field :meeting_date, class:"minutes-form", placeholder:"例)2021/01/01"%>
    </div>

    <div class="all_complete_date-form">
      <div class="form-title">
        タスク全項目終了予定日
        <br><span class="indispensable">（必須, ※ 西暦4桁/月/日 で登録してください)</span>
      </div>
      <%= f.text_field :all_complete_date, class:"minutes-form", placeholder:"例)2021/03/01"%>
    </div>

    <div class="content-form">
      <div class="form-title">
        会議内容
        <br><span class="indispensable">(必須)</span>
        </div>
      <%= f.text_area :content, class:"content_text_form", placeholder:"例)2021年から始動するAプロジェクトのキックオフを実施"%>
    </div>

    <div class="submit-form">
      <%= f.submit "登録する", class:"submit-btn" %>
    </div>

     <% end %>

    <%= link_to "トップページに戻る", root_path, class:"back-top-page"%>
</div>

app/views/minutes/index.html.erb
<header><%= render "shared/header" %></header>

<div class="main">
  <%# ピン留めリスト一覧 %>
  <div class ="side-bar">
  ★ピン留めリスト
    <% @minute_pin.each do |minute|%>
      <%= render partial:'short_minute', locals:{minute: minute} %>
    <% end%>
  </div>

  <div class="main-bar">
    <%# 検索窓 %>
    <div class="main-upper-bar">
      <%# フリーワード検索窓 %>
      <div class="main-search">
        <%= form_with(url:search_minutes_path, local: true, method: :get, class:"search-class") do |f| %>
          <%= f.text_field :keyword, placeholder:"検索したいワードを入力してください", class:"search-form" %>
          <%= f.submit "検索", class:"search-submit-btn" %>
        <% end %>
      </div>

      <%# ワンクリック検索窓 %>
      <div class="sub-search">
        <%= form_with(url:search_me_minutes_path, local: true, method: :get, class:"search-sub-class") do |f| %>
          <%= f.submit "▼自分が投稿した議事録を表示", class:"search-sub-submit-btn" %>
        <% end %>
        <%= form_with(url:search_not_close_minutes_path , local: true, method: :get, class:"search-sub-class") do |f| %>
          <%= f.submit "▼closedされていない議事録を表示", class:"search-sub-submit-btn" %>
        <% end %>
      </div>

    </div>

    <%# 議事録一覧を表示 %>
    <div class="main-lower-bar">
    ■議事録一覧
      <% @minutes.each do |minute|%>
        <%= render partial:'minute', locals:{minute: minute} %>
      <% end %>
    </div>
  </div>
</div>

<footer><%= render "shared/footer" %></footer>

app/views/minutes/new.html.erb
<div class="main-contents">
    <h2>■新規議事録 登録ページ</h2>

    <%= form_with(model:@minute, url:minutes_path, class:"form", local: true) do |f| %>
    <%= render "shared/error_messages", locals:{model: @minute}, model: f.object %>

    <div class="title-form">
      <div class="form-title">
        会議名
        <br><span class="indispensable">（必須）</span>
      </div>
      <%= f.text_field :title, class:"minutes-form", placeholder:"例)Aプロジェクト キックオフ会議"%>
    </div>

    <div class="project_name-form">
      <div class="form-title">
        プロジェクト名
        <br><span class="indispensable">（必須）</span>
      </div>
      <%= f.text_field :project_name, class:"minutes-form", placeholder:"例)Aプロジェクト"%>
    </div>

    <div class="participate_member-form">
      <div class="form-title">
        会議参加者
        <br><span class="indispensable">（必須）</span>
      </div>
      <%= f.text_area :participate_member, class:"minutes-form-area", placeholder:"例)X社X部 鈴木様, C課 田中さん"%>
    </div>

    <div class="meeting_date-form">
      <div class="form-title">
        会議開催日
        <br><span class="indispensable">（必須, ※ 西暦4桁/月/日 で登録してください)</span>
      </div>
      <%= f.text_field :meeting_date, class:"minutes-form", placeholder:"例)2021/01/01"%>
    </div>

    <div class="all_complete_date-form">
      <div class="form-title">
        タスク全項目終了予定日
        <br><span class="indispensable">（必須, ※ 西暦4桁/月/日 で登録してください)</span>
      </div>
      <%= f.text_field :all_complete_date, class:"minutes-form", placeholder:"例)2021/03/01"%>
    </div>

    <div class="content-form">
      <div class="form-title">
        会議内容
        <br><span class="indispensable">(必須)</span>
        </div>
      <%= f.text_area :content, class:"content_text_form", placeholder:"例)2021年から始動するAプロジェクトのキックオフを実施"%>
    </div>

    <div class="images-form">
      <div class="form-title">
        画像
        <br><span class="indispensable">(任意)</span>
      </div>
      <div class="click_up_load">
        <p>クリックしてファイルをアップロード</p>
        <%= f.file_field :images, name: 'minute[images][]', id:'minute_images' %>
      </div>  

      <div id="image-list"></div>

      <% @minute.images.each do |image|%>
        <%= image_tag image, class:'images'%>
      <% end %>
    </div>

    <div class="submit-form">
      <%= f.submit "登録する", class:"submit-btn" %>
    </div>

     <% end %>

    <%= link_to "トップページに戻る", root_path, class:"back-top-page"%>
</div>

app/views/minutes/show.html.erb
<header><%= render "shared/header" %></header>

<%# 議事録内容一覧 %>
<div class="main">
  <div class ="left-bar">
  ■議事録詳細内容
  <%# closed済みの議事録はclosedと表示される設定 %>
  <div class="close-display">
    <% if @minute.closes.present? %>
      <%= "この議事録は#{@minute.user.last_name}#{@minute.user.first_name}さんによりclosed設定済みです" %>
    <% end %>
  </div>

    <%# 編集・削除・closed設定バー（投稿したユーザーのみ設定できる） %>
    <div class="function-bar">
      <% if current_user.id == @minute.user_id %>
        <%= link_to "編集", edit_minute_path(@minute.id), class:"user-only-func-btn" %>
        <%= link_to "削除", minute_path(@minute.id), method: :delete, class:"user-only-func-btn" %>
        <% if @minute.closes.empty? %>
          <%= link_to "この議事録をclosedする", minute_closes_path(@minute.id), method: :post, class:"add-btn" %>
        <% else %>
          <%= link_to "この議事録を再openする", minute_close_path(@minute.id), method: :delete, class:"delete-btn" %>
        <% end %>
      <% end %>

      <%# ピン留め設定バー（各ユーザー設定可能機能） %>
      <div class="pin-btns", id="pin-btns", onclick="window.location.reload()">
        <% if Pin.where(user_id: current_user.id).where(minute_id: @minute.id).empty? %>
          <%= link_to "ピン留めに追加", minute_pins_path(@minute), method: :post, class:"add-btn" %>
        <% else %>
          <%= link_to "ピン留めを外す", minute_pin_path(@minute_pin), method: :delete, class:"delete-btn" %>
        <% end %>
      </div>

      <input type="button"  class="koshin-btn" value="更新" id="koshin">
    </div>

    <%# 議事録内容詳細 %>
    <div class="minute-iists">
      <li class="minute-list">
        <div class="info-title">
        会議名
        </div>
        <%= @minute.title %>
      </li>

      <li class="minute-list">
        <div class="info-title">
        プロジェクト名
        </div>
        <%= @minute.project_name %>
      </li>

      <li class="minute-list">
        <div class="info-title">
        会議参加者
        </div>
        <%= @minute.participate_member %>
      </li>

      <li class="minute-list">
        <div class="info-title">
        会議開催日
        </div>
        <%= @minute.meeting_date %>
      </li>

      <li class="minute-list">
        <div class="info-title">
        タスク全項目終了予定日
        </div>
        <%= @minute.all_complete_date %>
      </li>

      <li class="minute-list">
        <div class="info-title">
        会議内容
        </div>
        <%= @minute.content %>
      </li>

      <% if @minute.images.present?%>
        <li class="minute-list">
          <div class="info-title">
          添付ファイル
          </div>
          <div class="minute-image">
            <% @minute.images.each do |image|%>
              <%= image_tag image, class:'images'%>
            <% end %>
          </div>
        </li>
      <% end %>

    </div>
  </div>

  <%# To Doリストゾーン %>
  <div class="right-bar">
    <div class="right-upper-bar">
    ■To Do リスト
    <%# To Doリストの登録がなければ登録ボタンが表示される %>
    <% unless @to_do_list.present? %>
      <div class="to_do_input_form">
        <%= link_to "To Do リストを登録する", new_minute_to_do_list_path(@minute.id), class:"to_do_input_form_btn"%>
      </div>

    <%# To Doリスト投稿があれば編集ボタンが表示される %>
    <% else %>
    <div class="to_do_list_show">
      <div class="to_do_list_edit">
        <%= link_to "編集", edit_minute_to_do_list_path(@to_do_list.minute.id, @to_do_list.id), class:"to_do_list_edit_btn" %>
      </div>

      <%# To Do リスト一覧 %>
      <div class="to_do_list_contents">
        <li>
          <%if @to_do_list.checked_list1 == true %>
            <span class="cheked-mark">済</span>
          <% end %>
          <%= @to_do_list.list1 %>
        </li>

        <% if @to_do_list.list2.present?%>
          <li>
          <%if @to_do_list.checked_list2 == true %>
            <span class="cheked-mark">済</span>
          <% end %>
          <%= @to_do_list.list2 %>
        </li>
        <% end %>

        <% if @to_do_list.list3.present?%>
          <li>
          <%if @to_do_list.checked_list3 == true %>
            <span class="cheked-mark">済</span>
          <% end %>
          <%= @to_do_list.list3 %>
        </li>
        <% end %>

        <% if @to_do_list.list4.present?%>
          <li>
          <%if @to_do_list.checked_list4 == true %>
            <span class="cheked-mark">済</span>
          <% end %>
          <%= @to_do_list.list4 %>
        </li>
        <% end %>

        <% if @to_do_list.list5.present?%>
          <li>
          <%if @to_do_list.checked_list5 == true %>
            <span class="cheked-mark">済</span>
          <% end %>
          <%= @to_do_list.list5 %>
        </li>
        <% end %>

        <% if @to_do_list.list6.present?%>
          <li>
          <%if @to_do_list.checked_list6 == true %>
            <span class="cheked-mark">済</span>
          <% end %>
          <%= @to_do_list.list6 %>
        </li>
        <% end %>

        <% if @to_do_list.list7.present?%>
          <li>
          <%if @to_do_list.checked_list7 == true %>
            <span class="cheked-mark">済</span>
          <% end %>
          <%= @to_do_list.list7 %>
        </li>
        <% end %>

        <% if @to_do_list.list8.present?%>
          <li>
          <%if @to_do_list.checked_list8 == true %>
            <span class="cheked-mark">済</span>
          <% end %>
          <%= @to_do_list.list8 %>
        </li>
        <% end %>

        <% if @to_do_list.list9.present?%>
          <li>
          <%if @to_do_list.checked_list9 == true %>
            <span class="cheked-mark">済</span>
          <% end %>
          <%= @to_do_list.list9 %>
        </li>
        <% end %>

        <% if @to_do_list.list10.present?%>
          <li>
          <%if @to_do_list.checked_list10 == true %>
            <span class="cheked-mark">済</span>
          <% end %>
          <%= @to_do_list.list10 %>
        </li>
        <% end %>
      </div>

    </div>
    <% end %>
    </div>

    <%# コメントゾーン %>
    <div class="right-lower-bar">
    ■コメント欄
      <%# コメント一覧表示 %>
      <div class="comments">
        <% @comments.each do |comment|%>
          <div class="comment">

            <div class=comennt-contents>
              <%# 各コメントした人の姓名を表示 %>
              <div class="comment-user_name">
                <%= "#{comment.user.last_name} #{comment.user.first_name}" %>:
              </div>
              <%# 各コメント内容を表示 %>
              <div class="comment_content">
                <%= comment.title %> 
              </div>
            </div>
            <%# コメントしたのがログイン中のユーザーに限り編集・削除ボタン表示 %>
            <div class="comment-edit-destroy">
              <% if current_user.id == comment.user_id %>
                <%= link_to "編集", edit_minute_comment_path(comment.minute.id, comment.id), class:"comment-edit-destroy-btn" %>
                <%= link_to "削除", minute_comment_path(comment.minute.id, comment.id), method: :delete, class:"comment-edit-destroy-btn" %>
              <% end %>
            </div>

          </div>
        <% end %>

        <%# コメントが何も投稿されていなければ下記を表示 %>
        <div class="comment-exit">
          <% if @comments.present? %>
            この投稿に関するコメントは以上です。
          <% else %>
            この投稿にはコメントは投稿されていません。
          <% end %>
        </div>

        <br>
        <%=link_to "トップページに戻る", root_path%>

      </div>
        <%# コメント投稿ボタン %>
        <%= link_to "コメントする", new_minute_comment_path(@minute.id), class:"comment-button"%>
      </div>
    </div>
  </div>

</div>

<footer><%= render "shared/footer" %></footer>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="errors-alert">
  <ul>
    <% model.errors.full_messages.each do |message|%>
    <li class="error-message"><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer-contents">
  <%= "©︎gizigizi" %>
</div>

app/views/shared/_header.html.erb
<header class='top-page-header'>
  <div class="title-contents">
    <%= link_to "GiziGizi", "/", class:"title-logo"%>
  </div>

  <div class='nav'>
    <ul class="nav-lists">
      <% if user_signed_in? %>
        <li><%=link_to "新規議事録登録", new_minute_path, class:"nav-list"%></li>
        <li><%=link_to "ログアウト", destroy_user_session_path, method: :delete, class:"nav-list"%></li>
        <li><%= "#{current_user.last_name }#{current_user.first_name}さん" %>
      <% else %>
        <li><%=link_to "ログイン", new_user_session_path, class:"nav-list"%></li>
        <li><%=link_to "新規登録", new_user_registration_path, class:"nav-list"%></li>
      <% end %>
    </ul>
  </div>
</div>